# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
oned=np.array([1])

# Create a 2-dimensional NumPy array using np.array()
twod=np.array([[1,2,3],
              [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
threed=np.array([[[1,2,3],
                [4,5,6]],
                [[7,8,9],
                [10,11,12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
oned.ndim, oned.dtype, oned.size, type(oned)

(1, dtype('int32'), 1, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
twod.ndim, twod.dtype, twod.size, type(twod)

(2, dtype('int32'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
threed.ndim, threed.dtype, threed.size, type(threed)

(3, dtype('int32'), 12, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
a1=pd.DataFrame(oned)
a1
a2=pd.DataFrame(twod)
a2

0  1  2
0  1  2  3
1  4  5  6

In [7]:
# Create an array of shape (10, 2) with only ones
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros=np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
astep=np.random.randint(0,100,3)
astep

array([12, 15, 48])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a1_random=np.random.randint(0,10, size=(7,2))
a1_random

array([[0, 9],
       [6, 0],
       [3, 9],
       [7, 5],
       [2, 7],
       [3, 3],
       [7, 3]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a1_float=np.random.random((3,5))
a1_float

array([[6.17153531e-01, 8.57375287e-01, 9.68992765e-01, 8.36973362e-02,
        7.44790324e-01],
       [3.57775856e-01, 2.79859649e-01, 3.00515118e-01, 8.46277804e-01,
        8.23867647e-02],
       [8.63282071e-01, 8.51902735e-01, 6.72699817e-04, 7.21853251e-01,
        7.60859117e-01]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a2_random=np.random.randint(0,10, size=(7,2))
a2_random

array([[6, 3],
       [7, 4],
       [6, 9],
       [2, 6],
       [7, 4],
       [3, 7],
       [7, 2]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a3_var=np.random.randint(1,10, size=(3,7))
a3_var
# Find the unique numbers in the array you just created
np.unique(a3_var)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# Find the 0'th index of the latest array you created
a3_var[0]

array([6, 5, 2, 8, 6, 2, 5])

In [15]:
# Get the first 2 rows of latest array you created
a3_var[:2]

array([[6, 5, 2, 8, 6, 2, 5],
       [1, 6, 9, 1, 3, 7, 4]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
a3_var[:2, :2]

array([[6, 5],
       [1, 6]])

In [36]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array=np.random.randint(10, size=(3,5))
onesn=np.ones((3,5))
random_array

array([[7, 0, 7, 7, 2],
       [0, 7, 2, 2, 0],
       [4, 9, 6, 9, 8]])

In [33]:
onesn

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
# Add the two arrays together
random_array+onesn

array([[ 8.,  1.,  8.,  8.,  3.],
       [ 1.,  8.,  3.,  3.,  1.],
       [ 5., 10.,  7., 10.,  9.]])

In [20]:
# Create another array of ones of shape (5, 3)
onene=np.ones((5,3))
onene

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
# Try add the array of ones and the other most recent array together
random_array_reshape=random_array.reshape((3,5,1))
random_array_reshape+onene

array([[[ 8.,  8.,  8.],
        [ 1.,  1.,  1.],
        [ 8.,  8.,  8.],
        [ 8.,  8.,  8.],
        [ 3.,  3.,  3.]],

       [[ 1.,  1.,  1.],
        [ 8.,  8.,  8.],
        [ 3.,  3.,  3.],
        [ 3.,  3.,  3.],
        [ 1.,  1.,  1.]],

       [[ 5.,  5.,  5.],
        [10., 10., 10.],
        [ 7.,  7.,  7.],
        [10., 10., 10.],
        [ 9.,  9.,  9.]]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [42]:
# Create another array of ones of shape (3, 5)
ones=np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
# Subtract the new array of ones from the other most recent array
random_array-ones    

array([[ 6., -1.,  6.,  6.,  1.],
       [-1.,  6.,  1.,  1., -1.],
       [ 3.,  8.,  5.,  8.,  7.]])

In [45]:
# Multiply the ones array with the latest array
random_array*ones

array([[7., 0., 7., 7., 2.],
       [0., 7., 2., 2., 0.],
       [4., 9., 6., 9., 8.]])

In [46]:
# Take the latest array to the power of 2 using '**'
random_array**2

array([[49,  0, 49, 49,  4],
       [ 0, 49,  4,  4,  0],
       [16, 81, 36, 81, 64]])

In [49]:
# Do the same thing with np.square()
np.square(random_array)

array([[49,  0, 49, 49,  4],
       [ 0, 49,  4,  4,  0],
       [16, 81, 36, 81, 64]])

In [50]:
# Find the mean of the latest array using np.mean()
np.mean(random_array)

4.666666666666667

In [54]:
# Find the maximum of the latest array using np.max()
np.max(random_array, axis=0)

array([7, 9, 7, 9, 8])

In [55]:
# Find the minimum of the latest array using np.min()
np.min(random_array, axis=0)

array([0, 0, 2, 2, 0])

In [56]:
# Find the standard deviation of the latest array
np.std(random_array)

3.259175083088085

In [57]:
# Find the variance of the latest array
np.var(random_array)

10.622222222222224

In [58]:
# Reshape the latest array to (3, 5, 1)
random_array.reshape((3,5,1))

array([[[7],
        [0],
        [7],
        [7],
        [2]],

       [[0],
        [7],
        [2],
        [2],
        [0]],

       [[4],
        [9],
        [6],
        [9],
        [8]]])

In [59]:
# Transpose the latest array
random_array.T

array([[7, 0, 4],
       [0, 7, 9],
       [7, 2, 6],
       [7, 2, 9],
       [2, 0, 8]])

What does the transpose do? Ans: It converts the rows into columns and columns into rows

In [60]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
first=np.random.randint(10, size=(3,3))
second=np.random.randint(10, size=(3,2))

In [61]:
first

array([[6, 8, 7],
       [1, 0, 6],
       [6, 7, 4]])

In [62]:
second

array([[2, 7],
       [5, 2],
       [0, 2]])

In [63]:
# Perform a dot product on the two newest arrays you created
first.dot(second)

array([[52, 72],
       [ 2, 19],
       [47, 64]])

In [64]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
third=np.random.randint(10, size=(4,3))
fourth=np.random.randint(10, size=(4,3))

In [65]:
third

array([[4, 2, 0],
       [4, 9, 6],
       [6, 8, 9],
       [9, 2, 6]])

In [66]:
fourth

array([[0, 3, 3],
       [4, 6, 6],
       [3, 6, 2],
       [5, 1, 9]])

In [67]:
# Perform a dot product on the two newest arrays you created
third.dot(fourth)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [68]:
third.dot(fourth.T)

array([[  6,  28,  24,  22],
       [ 45, 106,  78,  83],
       [ 51, 126,  84, 119],
       [ 24,  84,  51, 101]])

In [69]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
third.dot(fourth.T)

array([[  6,  28,  24,  22],
       [ 45, 106,  78,  83],
       [ 51, 126,  84, 119],
       [ 24,  84,  51, 101]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [70]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a1=np.random.randint(10, size=(2,3))
a2=np.random.randint(10, size=(2,3))

In [71]:
a1

array([[8, 4, 5],
       [3, 9, 6]])

In [72]:
a2

array([[8, 6, 0],
       [0, 8, 8]])

In [73]:
# Compare the two arrays with '>'
a1>a2

array([[False, False,  True],
       [ True,  True, False]])

What happens when you compare the arrays with `>`?

In [74]:
# Compare the two arrays with '>='
a1>=a2

array([[ True, False,  True],
       [ True,  True, False]])

In [75]:
# Find which elements of the first array are greater than 7
a1>7

array([[ True, False, False],
       [False,  True, False]])

In [76]:
# Which parts of each array are equal? (try using '==')
a1==a2

array([[ True, False, False],
       [False, False, False]])

In [77]:
# Sort one of the arrays you just created in ascending order
np.sort(a1)

array([[4, 5, 8],
       [3, 6, 9]])

In [78]:
# Sort the indexes of one of the arrays you just created
np.argsort(a1)

array([[1, 2, 0],
       [0, 2, 1]], dtype=int64)

In [79]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a1)

4

In [80]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a1)

3

In [81]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.max(a1, axis=1)

array([8, 9])

In [82]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.min(a1, axis=0)

array([3, 4, 5])

In [83]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[ 0.29612028,  0.26105527,  0.00511346, -0.23458713, -1.41537074],
       [-0.42064532, -0.34271452, -0.80227727, -0.16128571,  0.40405086],
       [ 1.8861859 ,  0.17457781,  0.25755039, -0.07444592, -1.91877122]])

In [84]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.